# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79dc4b81309bca9fe503f7b388f181b18c3f16b725ca045d4c55e8f7b6cf92d9b6a863efa65ab55509c0b174f2e9e7a5d1d263f68064a65657b690943163070e

test:
  secret_key_base: 23d0a4d55cdf2e083fb81746ca40bab21333df67c6cd5400851a0f1a9f0e7e9f65e0eebd5a2188637aa5e79c25a0f94f312a8ab82d9f2d07c40622b56f152ec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
